# Generated by Django 3.2.4 on 2021-06-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugarList', '0004_auto_20210615_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productAddedSugar',
            field=models.BooleanField(default=False, verbose_name='Added Sugar'),
        ),
        migrations.AddField(
            model_name='product',
            name='productSize',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Size(g)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productBrand',
            field=models.CharField(max_length=250, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(upload_to='img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productSugar',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sugar(per 100g)'),
        ),
    ]
