# Generated by Django 3.2.4 on 2021-06-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugarList', '0006_alter_product_productaddedsugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productAddedSugar',
            field=models.BooleanField(default=False, verbose_name='Product has added sugar'),
        ),
    ]
